import sys
import re
import os
import matplotlib.pyplot as plt

if len(sys.argv) < 3:
    print("Usage: python3 plot_throughput.py <BW> \"<rtt_list_in_ms>\"")
    sys.exit(1)

bw_label = sys.argv[1]
# Convert the string "20 50 100..." into a list of integers
rtt_list = [int(rtt) for rtt in sys.argv[2].split()]

ledbat_throughputs = []
cubic_throughputs = []
valid_rtts = []

def extract_throughput(filename):
    """ Parses an iperf3 text file and returns the receiver bitrate in Mbit/s """
    if not os.path.exists(filename):
        return None
    
    with open(filename, 'r') as f:
        for line in f:
            # We look for the final summary line generated by the receiver
            if "receiver" in line:
                # Regex captures the number (Group 1) AND the unit prefix (Group 2)
                # It matches bits, Kbits, Mbits, or Gbits
                match = re.search(r'([\d.]+)\s+([KMG]?bits)/sec', line)
                if match:
                    value = float(match.group(1))
                    unit = match.group(2)
                    
                    # Normalize everything to Mbits/sec for the graph
                    if unit == "Kbits":
                        return value / 1000.0
                    elif unit == "Mbits":
                        return value
                    elif unit == "Gbits":
                        return value * 1000.0
                    elif unit == "bits":
                        return value / 1000000.0
                        
    return 0.0

print("Parsing iperf3 logs...")

# Extract data for each RTT
for rtt in rtt_list:
    l_file = f"logs/throughput_ledbat_{rtt}ms.txt"
    c_file = f"logs/throughput_cubic_{rtt}ms.txt"
    
    l_tput = extract_throughput(l_file)
    c_tput = extract_throughput(c_file)
    
    if l_tput is not None and c_tput is not None:
        valid_rtts.append(rtt)
        ledbat_throughputs.append(l_tput)
        cubic_throughputs.append(c_tput)
        print(f"RTT: {rtt}ms | LEDBAT: {l_tput} Mbit/s | CUBIC: {c_tput} Mbit/s")
    else:
        print(f"Warning: Missing logs for {rtt}ms. Skipping.")

# Plotting the Graph
plt.figure(figsize=(10, 6))

# Plot both lines with markers
plt.plot(valid_rtts, cubic_throughputs, label='CUBIC', color='red', marker='s', linewidth=2, markersize=8)
plt.plot(valid_rtts, ledbat_throughputs, label='LEDBAT', color='blue', marker='o', linewidth=2, markersize=8)

# Formatting the graph
plt.xlabel('Round Trip Time (ms)', fontweight='bold', fontsize=12)
plt.ylabel('Mean Throughput (Mbit/s)', fontweight='bold', fontsize=12)
plt.title(f'Mean Throughput vs RTT (Bottleneck: {bw_label})', fontsize=14, fontweight='bold')

# Set the Y-axis to start at 0 and go slightly above the max bandwidth (e.g., 22 for a 20Mbit link)
plt.ylim(0, int(bw_label.replace("Mbit/s", "")) + 2)

plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(loc='lower right', fontsize=12)
plt.tight_layout()

output_file = "throughput_vs_rtt.png"
plt.savefig(output_file, dpi=300)
print(f"\nSuccess! Graph saved as {output_file}")